namespace SMF.Domain.Entities;

/// <summary>
/// A shopper's working basket. Persisted server-side so the same cart shows
/// up across devices for signed-in members and across tabs for guests.
///
/// Identity:
///   * Guests pass an opaque <see cref="GuestKey"/> (UUID v4) generated by
///     the client and kept in localStorage.
///   * Members pass <see cref="MemberId"/> instead.
///   * Both can be set once the guest signs in — at which point we merge
///     the guest cart into the member cart (handler concern, not the
///     entity's).
/// </summary>
public class Cart
{
    public Guid Id { get; private set; }
    public Guid? MemberId { get; private set; }
    public Guid? GuestKey { get; private set; }
    public string Currency { get; private set; } = "SAR";
    public DateTime CreatedAtUtc { get; private set; }
    public DateTime UpdatedAtUtc { get; private set; }

    private readonly List<CartItem> _items = new();
    public IReadOnlyCollection<CartItem> Items => _items.AsReadOnly();

    public long SubtotalMinor => _items.Sum(i => i.LineTotalMinor);

    private Cart() { }

    public static Cart ForGuest(Guid guestKey, string currency, DateTime nowUtc)
    {
        if (guestKey == Guid.Empty)
            throw new ArgumentException("Guest key is required.", nameof(guestKey));
        if (string.IsNullOrWhiteSpace(currency) || currency.Length != 3)
            throw new ArgumentException("Currency must be ISO-4217.", nameof(currency));

        return new Cart
        {
            Id = Guid.NewGuid(),
            GuestKey = guestKey,
            Currency = currency.ToUpperInvariant(),
            CreatedAtUtc = nowUtc,
            UpdatedAtUtc = nowUtc
        };
    }

    public static Cart ForMember(Guid memberId, string currency, DateTime nowUtc)
    {
        if (memberId == Guid.Empty)
            throw new ArgumentException("Member id is required.", nameof(memberId));
        if (string.IsNullOrWhiteSpace(currency) || currency.Length != 3)
            throw new ArgumentException("Currency must be ISO-4217.", nameof(currency));

        return new Cart
        {
            Id = Guid.NewGuid(),
            MemberId = memberId,
            Currency = currency.ToUpperInvariant(),
            CreatedAtUtc = nowUtc,
            UpdatedAtUtc = nowUtc
        };
    }

    public void AssociateMember(Guid memberId)
    {
        if (memberId == Guid.Empty)
            throw new ArgumentException("Member id is required.", nameof(memberId));
        MemberId = memberId;
    }

    /// <summary>
    /// Add (or, when the SKU is already in the cart, accumulate) a line item.
    /// We snapshot the price + name onto the line so the user sees the same
    /// figures even if the catalog price moves between view and checkout.
    /// </summary>
    public CartItem AddItem(Product product, int quantity, DateTime nowUtc)
    {
        if (product is null) throw new ArgumentNullException(nameof(product));
        if (quantity <= 0)
            throw new ArgumentOutOfRangeException(nameof(quantity), "Quantity must be positive.");

        if (!string.Equals(product.Currency, Currency, StringComparison.OrdinalIgnoreCase))
            throw new InvalidOperationException(
                $"Cannot mix currencies in a cart. Cart is {Currency}, product '{product.Sku}' is {product.Currency}.");

        var existing = _items.FirstOrDefault(i => i.ProductId == product.Id);
        if (existing is not null)
        {
            existing.IncreaseQuantity(quantity);
            UpdatedAtUtc = nowUtc;
            return existing;
        }

        var item = CartItem.Create(Id, product, quantity);
        _items.Add(item);
        UpdatedAtUtc = nowUtc;
        return item;
    }

    public void UpdateQuantity(Guid productId, int quantity, DateTime nowUtc)
    {
        var item = _items.FirstOrDefault(i => i.ProductId == productId)
                   ?? throw new InvalidOperationException($"Product {productId} is not in the cart.");
        if (quantity <= 0)
        {
            _items.Remove(item);
        }
        else
        {
            item.SetQuantity(quantity);
        }
        UpdatedAtUtc = nowUtc;
    }

    public void RemoveItem(Guid productId, DateTime nowUtc)
    {
        var item = _items.FirstOrDefault(i => i.ProductId == productId);
        if (item is null) return;
        _items.Remove(item);
        UpdatedAtUtc = nowUtc;
    }

    public void Clear(DateTime nowUtc)
    {
        _items.Clear();
        UpdatedAtUtc = nowUtc;
    }
}
